"use client";

import React, { useEffect, useRef, useState } from "react";
import { AlertCircle, ShieldCheck, Loader2 } from "lucide-react";
import { embedDashboard } from "@superset-ui/embedded-sdk";

interface SupersetDashboardProps {
  title: string;
  description: string;
  embeddedId: string; // The UUID generated by Superset for embedding
}

export default function SupersetDashboard({
  title,
  description,
  embeddedId,
}: SupersetDashboardProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [error, setError] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  // 🔴 IMPORTANT: FILL IN YOUR SUPERSET DOMAIN HERE
  const supersetDomain = "http://localhost:8088";

  useEffect(() => {
    let isMounted = true;

    // If you haven't filled in the embeddedId yet, don't try to load
    if (embeddedId === "REPLACE_ME_WITH_EMBEDDED_ID") {
      setIsLoading(false);
      setError("Please provide a valid embeddedId from Apache Superset.");
      return;
    }

    const mountDashboard = async () => {
      if (!containerRef.current) return;

      setIsLoading(true);
      setError(null);

      try {
        await embedDashboard({
          id: embeddedId,
          supersetDomain: supersetDomain,
          mountPoint: containerRef.current,
          fetchGuestToken: async () => {
            const res = await fetch("/api/superset/guest-token", {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({ embeddedId }),
            });

            const data = await res.json();
            if (!res.ok)
              throw new Error(data.error || "Failed to fetch guest token");

            return data.token;
          },
          dashboardUiConfig: {
            hideTitle: true,
            hideChartControls: false,
            hideTab: true,
          },
        });
      } catch (err: any) {
        if (isMounted) {
          console.error("Superset Embedding Error:", err);
          setError(
            err.message ||
              "Failed to load the dashboard. Is Superset running and CORS configured?",
          );
        }
      } finally {
        if (isMounted) setIsLoading(false);
      }
    };

    mountDashboard();

    return () => {
      isMounted = false;
      if (containerRef.current) {
        containerRef.current.innerHTML = "";
      }
    };
  }, [embeddedId]);

  return (
    <div className="flex flex-col h-full bg-slate-950 p-6 overflow-hidden">
      <div className="mb-6 flex justify-between items-start">
        <div>
          <h1 className="text-3xl font-black italic tracking-tighter text-white">
            {title}
          </h1>
          <p className="text-slate-400 mt-1">{description}</p>
        </div>
        <div className="px-3 py-1.5 bg-emerald-900/30 border border-emerald-500/30 text-emerald-400 text-[10px] font-bold tracking-widest uppercase rounded flex items-center gap-2">
          <ShieldCheck className="w-4 h-4" /> Secure SDK Embedded
        </div>
      </div>

      <div className="flex-1 bg-slate-900 border border-slate-800 rounded-xl overflow-hidden relative shadow-2xl flex flex-col">
        {isLoading && (
          <div className="absolute inset-0 z-10 bg-slate-900/80 backdrop-blur-sm flex flex-col items-center justify-center text-indigo-400">
            <Loader2 className="w-8 h-8 animate-spin mb-4" />
            <div className="text-sm font-bold tracking-widest uppercase">
              Fetching Guest Token & Loading Superset...
            </div>
          </div>
        )}

        {error && (
          <div className="absolute inset-0 z-20 bg-slate-900 flex flex-col items-center justify-center p-8 text-center">
            <div className="w-16 h-16 bg-red-900/30 border border-red-500/50 rounded-full flex items-center justify-center mb-6">
              <AlertCircle className="w-8 h-8 text-red-500" />
            </div>
            <h3 className="text-xl font-bold text-white mb-2">
              Connection Failed
            </h3>
            <p className="text-slate-400 max-w-lg mb-6">{error}</p>

            <div className="bg-slate-950 border border-slate-800 p-6 rounded-lg text-left w-full max-w-2xl">
              <h4 className="font-bold text-indigo-400 mb-4 uppercase tracking-widest text-xs">
                Setup Checklist:
              </h4>
              <ul className="text-sm text-slate-300 space-y-3">
                <li>
                  1. <strong>Embedded ID:</strong> Have you replaced the{" "}
                  <code>embeddedId</code> in <code>page.tsx</code> with the UUID
                  from Superset?
                </li>
                <li>
                  2. <strong>Credentials:</strong> Have you entered your
                  Superset admin username/password in{" "}
                  <code>app/api/superset/guest-token/route.ts</code>?
                </li>
                <li>
                  3. <strong>Feature Flags:</strong> Is{" "}
                  <code>&quot;EMBEDDED_SUPERSET&quot;: True</code> enabled in
                  your <code>superset_config.py</code>?
                </li>
                <li>
                  4. <strong>CORS:</strong> Is <code>CORS_OPTIONS</code>{" "}
                  configured in Superset to allow requests from{" "}
                  <code>http://localhost:3000</code>?
                </li>
              </ul>
            </div>
          </div>
        )}

        <div
          ref={containerRef}
          className="w-full h-screen [&>iframe]:w-full [&>iframe]:h-full [&>iframe]:border-none"
        />
      </div>
    </div>
  );
}
