import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-950 text-slate-50 flex flex-col min-h-screen`}
      >
        <nav className="bg-slate-900 border-b border-slate-800 px-6 py-3 flex items-center justify-between z-50">
          <div className="flex items-center gap-6">
            <div className="font-black text-xl italic tracking-tighter text-indigo-500">
              SPRINT<span className="text-white">DSS</span>
            </div>
            <div className="flex gap-4">
              <Link
                href="/"
                className="text-sm font-bold text-slate-300 hover:text-white uppercase tracking-wider"
              >
                3D Digital Twin
              </Link>
              <Link
                href="/dashboard/current"
                className="text-sm font-bold text-slate-300 hover:text-white uppercase tracking-wider"
              >
                Current State Dashboard
              </Link>
              <Link
                href="/dashboard/solution"
                className="text-sm font-bold text-slate-300 hover:text-emerald-400 uppercase tracking-wider"
              >
                Solution Dashboard
              </Link>
            </div>
          </div>
        </nav>
        <main className="flex-1 flex flex-col overflow-hidden">{children}</main>
      </body>
    </html>
  );
}
